code --install-extension aaron-bond.better-comments
code --install-extension astro-build.astro-vscode
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension mikestead.dotenv
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension Orta.vscode-jest
code --install-extension Perkovec.emoji
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension rangav.vscode-thunder-client
code --install-extension sdras.night-owl
code --install-extension unifiedjs.vscode-mdx
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wix.vscode-import-cost
code --install-extension yzhang.markdown-all-in-one
