code --install-extension aaron-bond.better-comments
code --install-extension alexcvzz.vscode-sqlite
code --install-extension astro-build.astro-vscode
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension mikestead.dotenv
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension Orta.vscode-jest
code --install-extension Perkovec.emoji
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension Prisma.prisma
code --install-extension rangav.vscode-thunder-client
code --install-extension ritwickdey.LiveServer
code --install-extension ryuta46.multi-command
code --install-extension unifiedjs.vscode-mdx
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
