code --install-extension aaron-bond.better-comments
code --install-extension alexcvzz.vscode-sqlite
code --install-extension astro-build.astro-vscode
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension hediet.vscode-drawio
code --install-extension Ionic.ionic
code --install-extension mikestead.dotenv
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension onecentlin.laravel-blade
code --install-extension Orta.vscode-jest
code --install-extension Perkovec.emoji
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension rangav.vscode-thunder-client
code --install-extension ritwickdey.LiveServer
code --install-extension ryuta46.multi-command
code --install-extension sdras.night-owl
code --install-extension unifiedjs.vscode-mdx
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xdebug.php-debug
code --install-extension yzhang.markdown-all-in-one
