code --install-extension aaron-bond.better-comments
code --install-extension astro-build.astro-vscode
code --install-extension blanu.vscode-styled-jsx
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension bungcip.better-toml
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension howardzuo.vscode-npm-dependency
code --install-extension lextudio.restructuredtext
code --install-extension mikestead.dotenv
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension Orta.vscode-jest
code --install-extension Perkovec.emoji
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension rangav.vscode-thunder-client
code --install-extension ritwickdey.LiveServer
code --install-extension sdras.night-owl
code --install-extension TabNine.tabnine-vscode
code --install-extension unifiedjs.vscode-mdx
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.ReactSnippets
code --install-extension yzhang.markdown-all-in-one
